name: RailSwitch
version: '1.3.1'
main: sh.okx.railswitch.RailSwitch
author: Okx
api-version: '1.14'
description: Easily make rail switches for automated destination selection
softdepend: [Citadel, NameLayer]
commands:
  setdestination:
    usage: /<command> <destination>
    description: Set your rail destination
    aliases: [dest, destination, switch, setswitch, setsw]