name: ${project.artifactId}
version: ${project.version}
main: ${project.groupId}.${project.artifactId}Plugin
author: Okx
api-version: '1.12'
description: Easily make rail switches for automated destination selection
softdepend: [Citadel, NameLayer]
commands:
  setdestination:
    usage: /<command> <destination>
    description: Set your rail destination
    aliases: [dest, destination, switch, setswitch, setsw]
